### ISSUE TITLE
One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

### ISSUE THREAD

**Issue by ajaybirla-fabzen** [onedevapp/Unity_SmartCredentials#1]
Hi,

Thanks for the great Unity plugin!

It works well on devices below Android 14 but crashes on Android 14 and above. It seems to need an update for Android 14’s recent [behaviour changes](https://developer.android.com/about/versions/14/behavior-changes-14#runtime-receivers-exported).

> Caused by java.lang.SecurityException: com.empire.games: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
       at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
       at android.os.Parcel.createException(Parcel.java:3041)
       at android.os.Parcel.readException(Parcel.java:3024)
       at android.os.Parcel.readException(Parcel.java:2966)
       at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6086)
       at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1863)
       at android.app.ContextImpl.registerReceiver(ContextImpl.java:1803)
       at android.app.ContextImpl.registerReceiver(ContextImpl.java:1791)
       at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
       at com.onedevapp.smartcredentials.AuthManager.lambda$startListening$7$AuthManager(AuthManager.java:237)
       at com.onedevapp.smartcredentials.-$$Lambda$AuthManager$83UNibQrR_yTEJLrzSG11d2KFvI.onSuccess(:4)
       at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.1.0:1)
       at android.os.Handler.handleCallback(Handler.java:1000)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loopOnce(Looper.java:242)
       at android.os.Looper.loop(Looper.java:362)
       at android.app.ActivityThread.main(ActivityThread.java:8448)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)

**Comment by onedevapp** [comment]
Will provide a fix by tomo
